"""
DM Test: EGARCH(1,1) vs gcn-fusion on Brier score.

Requires `paper/revisions/egarch_test_scores.csv` (generated by
compute_m5_egarch_baseline.py) and
`research/bootstrap_rerun/final/predictions.csv`.

Loss functions:
  1. Brier score: (label - score)^2  for both models
  2. d[t] = loss_egarch[t] - loss_gcn[t]
     d_bar < 0 → EGARCH has lower Brier loss (better calibration)
     d_bar > 0 → GCN has lower Brier loss

Outputs:
  paper/revisions/dm_egarch_vs_gcn.json

Usage:
    cd <repo_root>
    python paper/revisions/compute_dm_egarch_vs_gcn.py
"""

from __future__ import annotations

import json
import os
import sys

import numpy as np
import pandas as pd
from scipy import stats

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

EGARCH_SCORES_CSV = os.path.join(REPO_ROOT, "paper", "revisions", "egarch_test_scores.csv")
PREDICTIONS_CSV   = os.path.join(REPO_ROOT, "research", "bootstrap_rerun", "final", "predictions.csv")
OUTPUT_JSON       = os.path.join(REPO_ROOT, "paper", "revisions", "dm_egarch_vs_gcn.json")


# ── Newey-West DM functions (copied from paper/compute_dm_test.py) ─────────────

def _newey_west_lrv(d: np.ndarray, H: int) -> float:
    T = len(d)
    dm = d - d.mean()
    gamma_0 = np.dot(dm, dm) / T
    lrv = gamma_0
    for h in range(1, H + 1):
        gamma_h = np.dot(dm[h:], dm[:-h]) / T
        weight = 1.0 - h / (H + 1)
        lrv += 2.0 * weight * gamma_h
    return lrv


def _dm_test(d: np.ndarray) -> dict:
    """Run DM test on loss differential d = loss_model1 - loss_model2."""
    T = len(d)
    d_bar = d.mean()
    H = int(np.floor(4.0 * (T / 100.0) ** (2.0 / 9.0)))
    lrv = _newey_west_lrv(d, H)
    if lrv <= 0:
        raise RuntimeError(f"Non-positive LRV: {lrv:.6g}")
    dm_stat = d_bar / np.sqrt(lrv / T)
    p_two   = float(2.0 * (1.0 - stats.norm.cdf(abs(dm_stat))))
    # p_egarch_better: one-tailed H1: EGARCH has lower Brier loss (d_bar < 0 → DM < 0)
    p_egarch_better = float(stats.norm.cdf(dm_stat))
    # p_gcn_better: one-tailed H1: GCN has lower Brier loss (d_bar > 0 → DM > 0)
    p_gcn_better    = float(1.0 - stats.norm.cdf(dm_stat))
    return {
        "T": int(T),
        "H_bandwidth": int(H),
        "d_bar": round(float(d_bar), 8),
        "lrv":   round(float(lrv), 10),
        "dm_stat": round(float(dm_stat), 4),
        "p_two_tailed": round(float(p_two), 4),
        "p_one_tailed_egarch_better": round(float(p_egarch_better), 4),
        "p_one_tailed_gcn_better":    round(float(p_gcn_better), 4),
    }


def main() -> None:
    print("Loading EGARCH per-sample scores ...")
    egarch_df = pd.read_csv(EGARCH_SCORES_CSV, parse_dates=["timestamp"])
    print(f"  {len(egarch_df):,} rows")

    print("Loading predictions.csv ...")
    pred_df = pd.read_csv(PREDICTIONS_CSV, parse_dates=["timestamp"])
    print(f"  {len(pred_df):,} rows")

    # Join on (symbol, timestamp)
    merged = pred_df.merge(
        egarch_df[["symbol", "timestamp", "egarch_score"]],
        on=["symbol", "timestamp"],
        how="left",
    )

    n_missing = merged["egarch_score"].isna().sum()
    if n_missing > 0:
        print(f"  WARNING: {n_missing} rows with no EGARCH score -> filling with 0.0")
    merged["egarch_score"] = merged["egarch_score"].fillna(0.0)

    y        = merged["label"].to_numpy(dtype=float)
    s_egarch = merged["egarch_score"].to_numpy(dtype=float)
    s_gcn    = merged["gcn_fusion_score"].to_numpy(dtype=float)

    print(f"\nTest observations: T={len(y):,}")
    print(f"  EGARCH score range: [{s_egarch.min():.4f}, {s_egarch.max():.4f}]")
    print(f"  GCN score range:    [{s_gcn.min():.4f}, {s_gcn.max():.4f}]")

    # Brier score losses
    loss_egarch = (y - s_egarch) ** 2
    loss_gcn    = (y - s_gcn)    ** 2

    # d[t] = loss_egarch - loss_gcn
    # d_bar < 0 → EGARCH better (lower Brier)
    # d_bar > 0 → GCN better
    d = loss_egarch - loss_gcn

    print(f"\n  Mean Brier loss (EGARCH): {loss_egarch.mean():.6f}")
    print(f"  Mean Brier loss (GCN):    {loss_gcn.mean():.6f}")
    print(f"  d_bar (EGARCH - GCN):     {d.mean():.6f}")

    result = _dm_test(d)

    dm_stat   = result["dm_stat"]
    p_two     = result["p_two_tailed"]
    p_egarch  = result["p_one_tailed_egarch_better"]
    p_gcn     = result["p_one_tailed_gcn_better"]

    if p_two > 0.05:
        conclusion = (
            f"DM stat = {dm_stat:.3f} (p = {p_two:.3f}, two-tailed). "
            f"The difference in Brier score between EGARCH(1,1) and gcn-fusion "
            f"is not statistically significant at alpha=0.05. "
            f"The two models are statistically comparable on probability calibration."
        )
    elif d.mean() < 0:
        conclusion = (
            f"DM stat = {dm_stat:.3f} (p = {p_two:.3f} two-tailed; "
            f"p = {p_egarch:.3f} one-tailed EGARCH better). "
            f"EGARCH(1,1) has significantly lower Brier score than gcn-fusion."
        )
    else:
        conclusion = (
            f"DM stat = {dm_stat:.3f} (p = {p_two:.3f} two-tailed; "
            f"p = {p_gcn:.3f} one-tailed GCN better). "
            f"gcn-fusion has significantly lower Brier score than EGARCH(1,1)."
        )

    output = {
        **result,
        "loss_egarch_mean": round(float(loss_egarch.mean()), 6),
        "loss_gcn_mean":    round(float(loss_gcn.mean()), 6),
        "conclusion": conclusion,
    }

    with open(OUTPUT_JSON, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nJSON saved: {OUTPUT_JSON}")
    print(f"Conclusion: {conclusion}")


if __name__ == "__main__":
    main()
